name: Smoke test

on: [workflow_dispatch, push, pull_request]

jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    env:
      id_label: test-container=pico-devcontainer
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install devcontainers CLI
      run: npm install -g @devcontainers/cli

    - name: Build and start devcontainer
      run: devcontainer up --id-label ${id_label} --workspace-folder .
    
    - name: Smoke test
      run: devcontainer exec --id-label ${id_label} --workspace-folder . /bin/bash -c "source ./tests/test-sdk-build.sh"
